### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by Thornaci** [andreacremaschi/GEOSwift#14]
Hi. I am new at apple. i can't  solve this. When i write pod install it gives error. When i delete pod geoswift it works. My podfile
source 'https://github.com/CocoaPods/Spces.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'GEOSwift'

**Comment by vfn** [comment]
@Thornaci can you please post the error message you are getting?

Have you read the note below, extracted from the readme file?

* Run `pod install`.

NOTE: running `pod install` may cause some errors if your machine does not have autoconf, automake and glibtool, if you encounter those errors you can run `brew install autoconf automake libtool` to install those packages and run again `pod install`.

**Comment by Thornaci** [comment]
Thornaci-MacBook-Pro:deneme Thornaci$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using Alamofire (3.1.3)
Installing GEOSwift (0.3.0)
Installing geos (3.4.2a)

[!] Error installing geos
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force https://svn.osgeo.org/geos/tags/3.4.2 /var/folders/jm/v6xncwpn3bx9t7lw55fb_lbr0000gn/T/d20151126-405-ooxwka

svn: E175002: Unable to connect to a repository at URL 'https://svn.osgeo.org/geos/tags/3.4.2'
svn: E175002: OPTIONS of 'https://svn.osgeo.org/geos/tags/3.4.2': Could not resolve hostname `svn.osgeo.org': Host not found (https://svn.osgeo.org)

**Comment by vfn** [comment]
@Thornaci are you behind a proxy by any chance?

Can you open the URL https://svn.osgeo.org/geos/tags/3.4.2 on your browser?

Have a look at how to setup svn to work with a proxy
http://stackoverflow.com/questions/1491180/how-to-configure-a-http-proxy-for-svn

**Comment by Thornaci** [comment]
Thank you the problem solved :)
