### ISSUE TITLE
Xcode 7.2 code completion

### ISSUE THREAD

**Issue by davidganster** [andreacremaschi/GEOSwift#15]
Hi,

I'm trying to use this pod in my project, but cannot get autocompletion in Swift to work using cocoa pods 0.39.0 (also tried 1.0.0.beta3).
Can somebody confirm that it works in their project?
If yes, are there some specific search header paths that need to be included?

I have successfully built `GEOSwift` on the `develop` branch (`master` seems broken), and code completion works in the playground.

**Comment by andreacremaschi** [comment]
I am using it.. did you remember to ```import GEOSwift```?

**Comment by davidganster** [comment]
Yes, I have that in my Swift file - the code compiles just fine, but code completion doesn't work.

I also tried importing `geos`, and importing the modules in the obejctive-c bridging header.

Which version of cocoapods are you using?
If it's not too much to ask, could you try setting up a clean project with just the `GEOSwift` pod and see if it works?

**Comment by andreacremaschi** [comment]
I just tried and everything seems ok: I created a new project, added the `Podfile`, added an ```import GEOSwift``` line in the AppDelegate and then added a ```let point = Waypoint(WKT: "POINT(45 9)")```. Autocompletion works too. I'm using CocoaPods 0.39.0, Xcode 7.2. Here is my Podfile:

```ruby
use_frameworks!

target 'testgeoswift' do
  pod 'GEOSwift'
end
```

**Comment by davidganster** [comment]
That's very strange.
I just tried the line of code you wrote, and I /do/ get autocompletion for the `point` variable.
However, as soon as I iterate over a collection of `GEOSwift` objects, autocompletion breaks.
Also, some of the extensions aren't recognised, for example `drawInSnapshot(snapshot:, mapRect:)`.

Does this give you any autocompletion for `geometry.`?

``` 
let geometriesArray = [Geometry]()
for geometry in geometriesArray {
  geometry.
}
```

**Comment by davidganster** [comment]
Hi again - it seems the issue lies with Xcode 7.2, not with `GEOSwift`. 
I noticed that the same problem appeared when using standard library objects (like `String`).

I just installed the 7.3 beta, and it works just fine now.

Thanks and sorry for the trouble.
