### ISSUE TITLE
Memory Leak suspicion

### ISSUE THREAD

**Issue by alsidor** [andreacremaschi/GEOSwift#19]
I have a geofencing app which create Waypoint at about every second.
I that case memory usage continuously grow till the OOM. Checked on the emulator and real devices.

(Geometry.deinit is called by the system)

**Comment by andreacremaschi** [comment]
Hi, I have never seen anything like this in the library. Can you create a sample project to reproduce the issue? Have you tried to debug your app with Instruments?

**Comment by alsidor** [comment]
I'll try to gather more information. There is a big chance I'll still
missing something in the app

On Friday, 4 March 2016, Andrea Cremaschi <notifications@github.com> wrote:

> Hi, I have never seen anything like this in the library. Can you create a
> sample project to reproduce the issue? Have you tried to debug your app
> with Instruments?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreacremaschi/GEOSwift/issues/19#issuecomment-192234784>
> .
>


-- 
S.P.Q.R.

**Comment by andreacremaschi** [comment]
Hey @alsidor, any news on this? I'll close the issue if not.

**Comment by alsidor** [comment]
Oh. Forgot about the issue.
It was no GeoSwift leak.
Sorry for inconvenience


On Sunday, 3 April 2016, Andrea Cremaschi <notifications@github.com> wrote:

> Hey @alsidor <https://github.com/alsidor>, any news on this? I'll close
> the issue if not.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/andreacremaschi/GEOSwift/issues/19#issuecomment-204867608>
>


-- 
S.P.Q.R.

**Comment by andreacremaschi** [comment]
No worries. Closing!
