### ISSUE TITLE
Error Include of non-modular header inside framework module geos

### ISSUE THREAD

**Issue by rzubeldia** [andreacremaschi/GEOSwift#20]
Hi, im having a problem when i try to run the example 

Include of non-modular header inside framework module geos, in file geos_c.h

Im running the project as we got from internet.

Any help?

Really appreciate

![geos-umbrella_h](https://cloud.githubusercontent.com/assets/1791418/14127856/8bf067b6-f5d8-11e5-8cb3-03d4410491d2.png)

**Comment by vfn** [comment]
@rzubeldia can you please checkout the develop branch and test if the issue is still happening there? I believe it got fixed by https://github.com/andreacremaschi/GEOSwift/commit/845aa2e2eeaac6586cdfd0b354d7ef87d1363d3e

**Comment by andreacremaschi** [comment]
mh I can see the issue too. Maybe it is related with Xcode 7.3 handling same-project modules in a new way, and breaking compatibility with playground? I didn't found confirm on this though.

**Comment by andreacremaschi** [comment]
Hi @rzubeldia, check if you are building the GEOSwift target for the __Simulator__ (not for a device)

**Comment by vfn** [comment]
@rzubeldia if you are still experiencing issues, please add a comment and we can reopen this issue and further investigate it
