### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nschucky** [andreacremaschi/GEOSwift#25]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by vfn** [comment]
@nschucky @andreacremaschi PR created: https://github.com/andreacremaschi/GEOSwift/pull/27

**Comment by falkobuttler** [comment]
@vfn do you plan to release a new version soon? Right now I would have to reference `master` directly to get Swift 3 support.

**Comment by vfn** [comment]
@falkobuttler please reference tag https://github.com/andreacremaschi/GEOSwift/tree/0.5 on your Podfile. I haven't been able to publish it yet due to issues when pushing it to Cocoapods trunk. I should be releasing it in the next couple of weeks

**Comment by vfn** [comment]
@nschucky @falkobuttler @andreacremaschi Swift 3 support is now officially available on `v0.5.1`. Tag https://github.com/andreacremaschi/GEOSwift/tree/0.5.1.

Cocoapods v1.1.1 fixed the issues I was having when publishing the podspec file.
