### ISSUE TITLE
Versions 0.4 & 0.5

### ISSUE THREAD

**Issue by vfn** [andreacremaschi/GEOSwift#28]
Hi @andreacremaschi 

I've prepared 2 new versions

- **Version 0.4:** that supports `Swift 2.x` and `Xcode 7 & 8` https://github.com/andreacremaschi/GEOSwift/tree/0.4
- **Version 0.5:** that supports `Swift 3` and `Xcode 8` only. https://github.com/andreacremaschi/GEOSwift/tree/0.5

I can publish the versions if you grant me access to the Cocoapods trunk:
`pod trunk add-owner GEOSwift virgiliofavero at gmail.com`

**Comment by andreacremaschi** [comment]
done!
