### ISSUE TITLE
Can't install pod

### ISSUE THREAD

**Issue by robcas3** [andreacremaschi/GEOSwift#29]
hi, i'm using the latest version of CocoaPods but the install process fails.
here's my output:

```bash
[!] /bin/bash -c 
set -e
type -P autoconf &>/dev/null || alias autoconf 'xcrun autoconf'
type -P autoheader &>/dev/null || alias autoheader 'xcrun autoheader'
type -P aclocal &>/dev/null || alias aclocal 'xcrun aclocal'
type -P automake &>/dev/null || alias automake 'xcrun automake'
type -P glibtool &>/dev/null || alias glibtool 'xcrun glibtool'
type -P glibtoolize &>/dev/null || alias glibtoolize 'xcrun glibtoolize'

sh autogen.sh
./configure
./tools/svn_repo_revision.sh

sed -i "" "s/\/\* #undef HAVE_INT64_T_64 \*\//#define HAVE_INT64_T_64 1/" include/geos/platform.h
sed -i "" "s/#define HAVE_LONG_INT_64 1/\/\* #undef HAVE_LONG_INT_64 \*\//" include/geos/platform.h

cat <<EOT >> include/geos/platform.h
  #undef ISNAN
  #define ISNAN(x) (std::isnan(x))
EOT

patch capi/geos_c.h <<EOF
  149c149
  < #include <geos/export.h>
 \---
  \> #define GEOS_DLL
EOF

/bin/bash: line 2: alias: autoconf: not found
/bin/bash: line 2: alias: xcrun autoconf: not found
```

**Comment by vfn** [comment]
Can you confirm what version of cocoapods and what version of GEOSwift you're using?

**Comment by robcas3** [comment]
i'm using version 1.0.0

**Comment by vfn** [comment]
I assume that's the Cocoapods version, right? What about GEOSwift? Can you also confirm the Xcode version?

**Comment by robcas3** [comment]
i'm sorry, i didn't read properly your comment. 
i'm using cocoa pods version 1.0.0 and version 0.4 of GEOSwift with 3.5.0 of geos

**Comment by vfn** [comment]
I haven't tested the latest version of GEOSwift with Cocoapods 1.0.0. Are you able to update Cocoapods to the latest (1.0.1)?

**Comment by robcas3** [comment]
i have updated to version 1.0.1 and i'm using it from terminal, but it gives me the same error

**Comment by vfn** [comment]
Xcode version?

**Comment by robcas3** [comment]
7.3

**Comment by vfn** [comment]
Cool. I read through your first message and found the problem.

You don't have all the dependencies installed. Have a look at the read me file for more info, but what you are missing is:

NOTE: running pod install may cause some errors if your machine does not have autoconf, automake and glibtool, if you encounter those errors you can run brew install autoconf automake libtool to install those packages and run again pod install.

**Comment by robcas3** [comment]
Thank you very much! This solves the problem!

**Comment by vfn** [comment]
👌
