### ISSUE TITLE
'geos/geos_c.h' file not found

### ISSUE THREAD

**Issue by jeffd** [andreacremaschi/GEOSwift#3]
Checked out the code from master, then built from CocoaPods and tried compiling the framework and I'm getting *'geos/geos_c.h' file not found* build errors in GEOSwiftCallback.h at Line 9.

I originally had trouble running *pod install* but followed the instructions in the README and after installing autoconf, automake and glibtool I was able to get *pod install* working.

I am trying to compile from the .xcworkspace

**Comment by andreacremaschi** [comment]
Hi,
just try cloning the project and execute ```pod install``` again from scratch, you seem to experience this same issue: https://github.com/andreacremaschi/SpatialDBKit/issues/24
