### ISSUE TITLE
No method mapboxShape

### ISSUE THREAD

**Issue by kondranton** [andreacremaschi/GEOSwift#32]
![screen shot 2016-11-23 at 17 51 47](https://cloud.githubusercontent.com/assets/9914409/20566303/9ba85680-b1a5-11e6-9417-1cd382ea4c83.png)

Somehow compiler doesn't see `mapboxShape` method

**Comment by vfn** [comment]
@kondranton can you post your project's podfile? If not, can you check if you are using the `MapboxGL` subspec?

**Comment by kondranton** [comment]
No, I don't use it, can you tell me how to add it, please?

**Comment by vfn** [comment]
Use `pod 'GEOSwift/MapboxGL'` instead of `pod 'GEOSwift'`

**Comment by kondranton** [comment]
Thanks a lot. That worked.
