### ISSUE TITLE
Can't not parse openstreet geojson

### ISSUE THREAD

**Issue by BoshiLee** [andreacremaschi/GEOSwift#35]
How to pares the geojson which converted form openstreetmap?
It's awalys throws fail...

https://www.dropbox.com/s/zcuii3ciplpebk6/taipei.geojson?dl=0

**Comment by vfn** [comment]
What error is it throwing?

**Comment by vfn** [comment]
@BoshiLee if you are still experiencing this issue, please create a new one with more information
