### ISSUE TITLE
Objective-C LineString usage

### ISSUE THREAD

**Issue by alexisbar** [andreacremaschi/GEOSwift#40]
Hi, 
First, let me thanks you for this amazing framework. I've tried many, proprietary or not, but this one is by far the best available for my needs.

I'm trying to integrate it into an Objc app. 
Here's what I've got working : 

`NSString *WKT = @"LINESTRING(5.220477 45.172999, 5.258071 45.160170 , 5.244166 45.169247)";
LineString *linestring = (LineString *)[Geometry create:WKT];`

Now, I'd like to get references to first and last point of linestring. Something like 

`startPoint = linestring.points[0] 
endPoint = linestring.points[linestring.numberOfPoints-1]`

Is this possible ? From what I see, LineString class has a CoordinatesCollection var named points, but I'm unable to access it.

<img width="620" alt="capture d ecran 2017-04-05 a 10 23 53" src="https://cloud.githubusercontent.com/assets/8861304/24696547/1837ceea-19ea-11e7-884e-c676fc508710.png">

**Comment by vfn** [comment]
Hi @alexisbar,

I'm afraid that's not possible. `CoordinatesCollection` is visible to Objective-C code as it is a `struct`.

If you'd like to still use `GEOSwift`, I would advise you to write a swift adapter class, that exposes the `points` property as a different type, (e.g. an `NSArray`), and make your Objective-C use this adapter class to get the information you need.

As an example, the code below works fine:

```Swift
import Foundation

import GEOSwift

public extension LineString {

    public func objc_points() -> PointsCollection {
        return PointsCollection(points: self.points)
    }

    public var test123: Int { return 10 }

}

public final class PointsCollection: NSObject {

    init(points: CoordinatesCollection) {
        self.points = points
    }

    private let points: CoordinatesCollection

    subscript(index: UInt32) -> CoordinatePoint {
        let coordinate = points[index]
        return CoordinatePoint(coordinate: coordinate)
    }

}

public final class CoordinatePoint: NSObject {
    public let x: CoordinateDegrees
    public let y: CoordinateDegrees
    fileprivate init(coordinate: Coordinate) {
        self.x = coordinate.x
        self.y = coordinate.y
    }
}
```

```Objecive-C
NSString *WKT = @"LINESTRING(5.220477 45.172999, 5.258071 45.160170 , 5.244166 45.169247)";
LineString *linestring = (LineString *)[Geometry create:WKT];
PointsCollection *points = linestring.objc_points;
CoordinatePoint *firstPoint = points[0];
NSLog(@"Point at index 0: (%f, %f)", firstPoint.x, firstPoint.y);
```

Hopefully that will help you.

**Comment by alexisbar** [comment]
Well that's perfect, I didn't knew about these adapters. Nice feature.

Just missing a public parameter for the PointsCollection subscript method to be seen by the objc interface header :

`public subscript(index: UInt32) -> CoordinatePoint {`

Thanks a lot !
