### ISSUE TITLE
pod geos error

### ISSUE THREAD

**Issue by badmonkeyemail** [andreacremaschi/GEOSwift#49]
the config.log below is:

configure:3545: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3556: $? = 1
configure:3545: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:3556: $? = 1
configure:3576: checking whether the C compiler works
configure:3598: gcc  /usr/local/opt/libxml2/include /usr/local/opt/libxml2/lib conftest.c  >&5
ld: can't map file, errno=22 file '/usr/local/opt/libxml2/lib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vfn** [comment]
Hi @badmonkeyemail,

If you look at the second last line of the log you posted above, `ld: can't map file, errno=22 file '/usr/local/opt/libxml2/lib' for architecture x86_64` it looks to be an issue with `libxml2`

Please share the whole log, if possible as it will make it easier to understand where the problem is

**Comment by badmonkeyemail** [comment]
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = zhanghaoxi.siweidg.com
uname -m = x86_64
uname -r = 16.6.0
uname -s = Darwin
uname -v = Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64
Kernel configured for up to 4 processors.
4 processors are physically available.
4 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3
Primary memory available: 8.00 gigabytes
Default processor set: 318 tasks, 1396 threads, 4 processors
Load average: 1.78, Mach factor: 2.20
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Users/siweidg/.rvm/gems/ruby-2.2.2/bin
PATH: /Users/siweidg/.rvm/gems/ruby-2.2.2@global/bin
PATH: /Users/siweidg/.rvm/rubies/ruby-2.2.2/bin
PATH: /Users/siweidg/.rvm/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /Library/Frameworks/Mono.framework/Versions/Current/Commands


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2510: checking build system type
configure:2524: result: x86_64-apple-darwin16.6.0
configure:2544: checking host system type
configure:2557: result: x86_64-apple-darwin16.6.0
configure:2577: checking target system type
configure:2590: result: x86_64-apple-darwin16.6.0
configure:2652: checking for a BSD-compatible install
configure:2720: result: /usr/local/bin/ginstall -c
configure:2731: checking whether build environment is sane
configure:2786: result: yes
configure:2937: checking for a thread-safe mkdir -p
configure:2976: result: /usr/local/bin/gmkdir -p
configure:2983: checking for gawk
configure:3013: result: no
configure:2983: checking for mawk
configure:3013: result: no
configure:2983: checking for nawk
configure:3013: result: no
configure:2983: checking for awk
configure:2999: found /usr/bin/awk
configure:3010: result: awk
configure:3021: checking whether make sets $(MAKE)
configure:3043: result: yes
configure:3072: checking whether make supports nested variables
configure:3089: result: yes
configure:3208: checking whether to enable maintainer-specific portions of Makefiles
configure:3217: result: no
configure:3280: checking for gcc
configure:3296: found /usr/bin/gcc
configure:3307: result: gcc
configure:3536: checking for C compiler version
configure:3545: gcc --version >&5
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
configure:3556: $? = 0
configure:3545: gcc -v >&5
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:3556: $? = 0
configure:3545: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3556: $? = 1
configure:3545: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:3556: $? = 1
configure:3576: checking whether the C compiler works
configure:3598: gcc  /usr/local/opt/libxml2/include /usr/local/opt/libxml2/lib conftest.c  >&5
ld: can't map file, errno=22 file '/usr/local/opt/libxml2/lib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3602: $? = 1
configure:3640: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3645: error: in `/Users/siweidg/Library/Caches/CocoaPods/Pods/Release/geos/3.5.0-e96c6':
configure:3647: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-apple-darwin16.6.0
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value=/usr/local/opt/libxml2/include
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value=/usr/local/opt/libxml2/lib
ac_cv_env_LIBS_set=set
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-apple-darwin16.6.0
ac_cv_path_install='/usr/local/bin/ginstall -c'
ac_cv_path_mkdir=/usr/local/bin/gmkdir
ac_cv_prog_AWK=awk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes
ac_cv_target=x86_64-apple-darwin16.6.0
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /Users/siweidg/Library/Caches/CocoaPods/Pods/Release/geos/3.5.0-e96c6/missing aclocal-1.15'
ALLOCA=''
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_CFLAGS=''
AM_CXXFLAGS=''
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR=''
AS=''
AUTOCONF='${SHELL} /Users/siweidg/Library/Caches/CocoaPods/Pods/Release/geos/3.5.0-e96c6/missing autoconf'
AUTOHEADER='${SHELL} /Users/siweidg/Library/Caches/CocoaPods/Pods/Release/geos/3.5.0-e96c6/missing autoheader'
AUTOMAKE='${SHELL} /Users/siweidg/Library/Caches/CocoaPods/Pods/Release/geos/3.5.0-e96c6/missing automake-1.15'
AWK='awk'
CAPI_INTERFACE_AGE='9'
CAPI_INTERFACE_CURRENT='10'
CAPI_INTERFACE_REVISION='0'
CAPI_VERSION='1.9.0'
CAPI_VERSION_MAJOR='1'
CAPI_VERSION_MINOR='9'
CAPI_VERSION_PATCH='0'
CC='gcc'
CCDEPMODE=''
CFLAGS=''
CPP=''
CPPFLAGS='/usr/local/opt/libxml2/include'
CXX=''
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
ENABLE_PHP_FALSE=''
ENABLE_PHP_TRUE=''
ENABLE_PYTHON_FALSE=''
ENABLE_PYTHON_TRUE=''
ENABLE_RUBY_FALSE=''
ENABLE_RUBY_TRUE=''
ENABLE_SWIG_FALSE=''
ENABLE_SWIG_TRUE=''
EXEEXT=''
FGREP=''
GREP=''
HAVE_PHP_FALSE=''
HAVE_PHP_TRUE=''
HAVE_PHP_UNIT_FALSE=''
HAVE_PHP_UNIT_TRUE=''
INLINE_FLAGS=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
INTERFACE_AGE=''
INTERFACE_CURRENT=''
INTERFACE_REVISION=''
JTS_PORT='1.13.0'
LD=''
LDFLAGS='/usr/local/opt/libxml2/lib'
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /Users/siweidg/Library/Caches/CocoaPods/Pods/Release/geos/3.5.0-e96c6/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/usr/local/bin/gmkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='geos'
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
PHP=''
PHPUNIT=''
PHP_CONFIG=''
PYTHON=''
PYTHON_CPPFLAGS=''
PYTHON_EXEC_PREFIX=''
PYTHON_EXTRA_LIBS=''
PYTHON_LDFLAGS=''
PYTHON_PLATFORM=''
PYTHON_PREFIX=''
PYTHON_SITE_PKG=''
PYTHON_VERSION=''
RANLIB=''
RUBY=''
RUBY_BIN_DIR=''
RUBY_EXTENSION_DIR=''
RUBY_INCLUDE_DIR=''
RUBY_LIB_DIR=''
RUBY_SHARED_LIB=''
RUBY_SITE_ARCH=''
RUBY_SO_NAME=''
RUBY_VERSION='ruby-2.2.2'
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
SWIG=''
SWIG_LIB=''
SWIG_PYTHON_CPPFLAGS=''
SWIG_PYTHON_OPT=''
VERSION='3.5.0'
VERSION_MAJOR='3'
VERSION_MINOR='5'
VERSION_PATCH='0'
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-apple-darwin16.6.0'
build_alias=''
build_cpu='x86_64'
build_os='darwin16.6.0'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-apple-darwin16.6.0'
host_alias=''
host_cpu='x86_64'
host_os='darwin16.6.0'
host_vendor='apple'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /Users/siweidg/Library/Caches/CocoaPods/Pods/Release/geos/3.5.0-e96c6/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
pkgpyexecdir=''
pkgpythondir=''
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
pyexecdir=''
pythondir=''
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='x86_64-apple-darwin16.6.0'
target_alias=''
target_cpu='x86_64'
target_os='darwin16.6.0'
target_vendor='apple'

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77

**Comment by vfn** [comment]
@badmonkeyemail, can you please provide your Podfile? And if possible, to create a sample project that I could clone and look at the issue.

**Comment by badmonkeyemail** [comment]
Hi @vfn,
Thank you for your reply.

I used the geoswift project, and I deleted GEOSwift.xcworkspace file because it's error:

diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

my podfile is
# Uncomment this line to define a global platform for your project
platform :ios, ’10.0’

use_frameworks!

target 'GEOSwift' do
  pod 'GEOSwift'
  pod 'geos'
  pod 'CocoaLumberjack'
end

target 'GEOSwiftTests' do
  pod 'GEOSwift'
  pod 'geos'
  pod 'CocoaLumberjack'
end

Thank you for your help.

**Comment by vfn** [comment]
Hi @badmonkeyemail, I don't believe that deleting `GEOSwift.xcworkspace` was the correct action. The error message clearly stated what was the issue:

diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

You should first run `pod install` and then you can try to build the project again.

If that doesn't solve your problem, please create a sample project and share the URL here.

Thanks!

**Comment by badmonkeyemail** [comment]
Hi @vfn ,
I upload my project. https://github.com/badmonkeyemail/test-geoswift
Please help.
Thank you.

**Comment by vfn** [comment]
@badmonkeyemail, Thank you for creating the repo. I cloned it and it worked just fine on my machine. After cloning, I run `pod install`, and then opened `GEOSwift.xcworkspace`. The project builds with no issues. ¯\_(ツ)_/¯

**Comment by badmonkeyemail** [comment]
Hi @vfn , it's too strange! What should I do? I guess the problem is maybe my environment or setting. This is parameters of my mac:
mac 10.12.5
Xcode 8.3.2 (8E2002)

gcc-4.9 (Homebrew GCC 4.9.4) 4.9.4 
--- I don't use clang，because https://svn.osgeo.org/geos/trunk/INSTALL said "OS/X 10.6, compile with gcc-4.0 rather than the default gcc that comes with XCode.  CC=gcc-4.0 CXX=g++-4.0 ./configure" ,
and I used clang at first but it's still error.

ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
gem 2.6.7
pod 1.2.1
Homebrew 1.2.3
libxml2 2.9.4_3
 
Anything wrong? 

Thanks.

**Comment by vfn** [comment]
@badmonkeyemail I can't see anything wrong with your setup. Could you explain what you are trying to do? Are you trying to integrate GEOSwift into an existing project or are you planing to do some development on the GEOSwift code itself?

**Comment by badmonkeyemail** [comment]
@vfn , My app need to draw vector data and my render engine supports geometry object. For simple vector data, like 'Polygon((0 0, 10 0, 10 10, 0 10, 0 0))', is ok, but same special complex data, which has a hole in the polygon or multi features, displays wrong. So I need geoSwift to parse vector data to correct geometry object. Is there anything else I can do without geoSwift?

**Comment by vfn** [comment]
@badmonkeyemail, could you try cloning the GEOSwift repo again? Then on terminal, type `pod install` and the proceed to open the `GEOSwift.xcworkspace` file.

Let me know it the pod will fail to build. if it fails, please create a repo and push this new project

**Comment by badmonkeyemail** [comment]
Hi @vfn , I think the problem is about configure geos, the log said,

configure:3545: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin16/4.9.4/lto-wrapper
Target: x86_64-apple-darwin16
Configured with: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_gcc49/gcc49/work/gcc-4.9.4/configure --prefix=/opt/local --build=x86_64-apple-darwin16 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc49 --includedir=/opt/local/include/gcc49 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-4.9 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.9 --with-gxx-include-dir=/opt/local/include/gcc49/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --disable-isl-version-check --with-cloog=/opt/local --disable-cloog-version-check --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc49 4.9.4_1' --with-build-config=bootstrap-debug
Thread model: posix
gcc version 4.9.4 (MacPorts gcc49 4.9.4_1) 
configure:3556: $? = 0
configure:3545: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3556: $? = 1
configure:3545: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3556: $? = 1
configure:3576: checking whether the C compiler works
configure:3598: gcc  /usr/local/opt/libxml2/include /usr/local/opt/libxml2/lib conftest.c  >&5
ld: can't map file, errno=22 file '/usr/local/opt/libxml2/include' for architecture x86_64
collect2: error: ld returned 1 exit status
configure:3602: $? = 1
configure:3640: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3645: error: in `/Users/siweidg/Library/Caches/CocoaPods/Pods/Release/geos/3.5.0-e96c6':
configure:3647: error: C compiler cannot create executables

There were three error bothered me, they caused geos compilation terminated.
gcc: error: unrecognized command line option '-V'
gcc: error: unrecognized command line option '-qversion'
ld: can't map file, errno=22 file '/usr/local/opt/libxml2/include' for architecture x86_64

Anyway, thank you a lof, I will try again.

**Comment by badmonkeyemail** [comment]
Hi @vfn , My friend compiled it okey. I feel very sad. Your project has no problem, its my  fault.
I will colse it, and thanks your help again.

**Comment by vfn** [comment]
@badmonkeyemail no problems! Please consider creating a pull request with your changes once you've finished them.
