### ISSUE TITLE
There is no way to create Geometry objects from coordinates

### ISSUE THREAD

**Issue by alsidor** [andreacremaschi/GEOSwift#5]
Hi. 
Looks like it's not possible to create Waypoint or Polygon or any other Geometry from given coordinates.
But it would be very useful. Like in ShapeKit.

Could you add this initialisers?

Thanks in advance
Alexander

**Comment by andreacremaschi** [comment]
Hey I finally added this in develop: https://github.com/andreacremaschi/GEOSwift/commit/f36c3d44b94a4f543cb9f7161cd6910ca6c30b91 
It takes me a while, sorry! It will be available in the next release (0.3.2)

**Comment by alsidor** [comment]
Thank you!
Looking forward to use the next release.

**Comment by hvbnet** [comment]
could you please make public init for Coordinate struct. I can't create instance of this class on swift 2.1
public struct Coordinate {
    public let x: Double
    public let y: Double
    public init(x: Double, y: Double) {
        self.x = x
        self.y = y
    }
}

**Comment by NiteshKumar-webonise** [comment]
hi, I have created one polygon on mapbox and I need to have its buffered polygon at some given distance lets say 10 meters, and also its coordinates as well. is this possible to achieve this by using GEOSwift ?
