### ISSUE TITLE
Xcode 7 / Swift 2 compatibility

### ISSUE THREAD

**Issue by Neku** [andreacremaschi/GEOSwift#6]
The project doesn't currently compile on Xcode 7 and doesn't seem easy to fix.
Is anyone currently on it?

**Comment by andreacremaschi** [comment]
Yes, there is a branch "feature/Swift-2.0" ready to be released. You can already make the pod declaration in your ```Podfile``` point to that branch if you need it.

**Comment by Neku** [comment]
Tried to merge it to master with little success.
I'll wait. Thank you and keep up the good work.

**Comment by vinz84** [comment]
This Branch will not compile for objective-c Project…

```@import GEOSwift;
…
    NSArray* tmpPoly = [Geometry fromGeoJSON:fileURL];
```

Will display: "Use of undeclared identifier 'Geometry'"

Any ideas to fix this problem?

**Comment by Neku** [comment]
I think atm it doesn't even work for swift2

**Comment by andreacremaschi** [comment]
Hey I've just released the version 0.3.0, now it should be working with Xcode 7+ and Swift 2+
@vinz84 are you still trying to integrate it in your Objective-C project? Is it working for you?

**Comment by andreacremaschi** [comment]
no answers. well, it is working for me, so.. :)
closing
