### ISSUE TITLE
MKShapesCollection doesn't expose his shapes array

### ISSUE THREAD

**Issue by Neku** [andreacremaschi/GEOSwift#7]
When I was trying to render the my shapes collection as on overlay on a MKMapView I realised that shapes wasn't public.
This: https://github.com/Neku/GEOSwift/commit/ab599efddc365416c91bcd650b877fda6b6d34c2 fixed it for me, but I was wondering if it is a mistake or there is some other way to get them.

**Comment by andreacremaschi** [comment]
No no you're correct, my mistake!
Thanks

**Comment by andreacremaschi** [comment]
fixed on branch ```Swift-2.0```: https://github.com/andreacremaschi/GEOSwift/commit/932317c98ddc48fd18cbade1b1af5982293e81bf
