### ISSUE TITLE
Circle functionality?

### ISSUE THREAD

**Issue by chriswiggins** [andreacremaschi/GEOSwift#8]
Loving this framework, makes parsing GeoJSON so much simpler! 

Looking to extend the functionality in here by adding support for circles. GeoJSON doesn't strictly have a "Circle" feature however convention states that you create a Point and then in the properties for the feature you have the radius.

Happy to submit a PR but just wondering where the best place to start would be.

Cheers

**Comment by chriswiggins** [comment]
MapKit supports Circles with its MKCircle class too

**Comment by andreacremaschi** [comment]
Hi Chris,

thank you for your love for the project! :beer: 

I see two issues with integrating support for circles into GEOSwift. 
The first, easy one: the GEOJSON parser at the moment just ignores the features' properties. I have in plan to add support for them but actually it is not possible. 
The second one is that the project is based on a C library named GEOS, that doesn't support circles. Nothing prevents us to extend features over the original project, but I would advise against introducing different primitives. 

As a workaround you can try to do this (I didn't actually test it):

```swift
        if let point = Waypoint(WKT: "POINT(9 45)") {
            let radius = 1.13
            if let circlePolygon = point.buffer(width: radius),
                let overlay = circlePolygon.mapShape() as? MKOverlay {
                self.mapView().addOverlay( overlay )
            }
        }
```

Does this work for you?

Cheers

**Comment by chriswiggins** [comment]
Yeah, that works fine for me! I suppose I'll just need to check whether or not the properties object has a radius specified and if so apply the necessary modifications

Thanks so much.

**Comment by andreacremaschi** [comment]
Ok happy to hear
